// SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.15;

import {Test} from "forge-std/Test.sol";
import {CometWithExtendedAssetList} from "../../../contracts/CometWithExtendedAssetList.sol";
import {CometConfiguration} from "../../../contracts/CometConfiguration.sol";
import {CometStorage} from "../../../contracts/CometStorage.sol";
import {CometInterface} from "../../../contracts/CometInterface.sol";
import {CometExtAssetList} from "../../../contracts/CometExtAssetList.sol";
import {AssetListFactory} from "../../../contracts/AssetListFactory.sol";
import {FaucetToken} from "../../../contracts/test/FaucetToken.sol";
import {SimplePriceFeed} from "../../../contracts/test/SimplePriceFeed.sol";
import {CometHandler} from "./CometHandler.sol";

import {console} from "forge-std/console.sol";

contract CometInvariantTest is Test, CometConfiguration {
    CometWithExtendedAssetList public comet;
    FaucetToken public base;
    FaucetToken public weth;
    SimplePriceFeed public basePriceFeed;
    SimplePriceFeed public wethPriceFeed;
    CometHandler public handler;

    function setUp() public {
        base = new FaucetToken(0, "USD Coin", 6, "USDC");
        weth = new FaucetToken(0, "Wrapped ETH", 18, "WETH");
        basePriceFeed = new SimplePriceFeed(1e8, 8);
        wethPriceFeed = new SimplePriceFeed(2000e8, 8);

        AssetListFactory factory = new AssetListFactory();
        ExtConfiguration memory extConfig = ExtConfiguration({name32: "Compound USDC", symbol32: "cUSDCv3"});
        CometExtAssetList ext = new CometExtAssetList(extConfig, address(factory));

        AssetConfig[] memory assets = new AssetConfig[](1);
        assets[0] = AssetConfig({
            asset: address(weth),
            priceFeed: address(wethPriceFeed),
            decimals: 18,
            borrowCollateralFactor: 0.8e18,
            liquidateCollateralFactor: 0.85e18,
            liquidationFactor: 0.95e18,
            supplyCap: 1_000_000e18
        });

        Configuration memory config = Configuration({
            governor: address(this),
            pauseGuardian: address(this),
            baseToken: address(base),
            baseTokenPriceFeed: address(basePriceFeed),
            extensionDelegate: address(ext),
            supplyKink: 0.8e18,
            supplyPerYearInterestRateSlopeLow: 0.04e18,
            supplyPerYearInterestRateSlopeHigh: 0.4e18,
            supplyPerYearInterestRateBase: 0,
            borrowKink: 0.8e18,
            borrowPerYearInterestRateSlopeLow: 0.05e18,
            borrowPerYearInterestRateSlopeHigh: 0.5e18,
            borrowPerYearInterestRateBase: 0.01e18,
            storeFrontPriceFactor: 0.5e18,
            trackingIndexScale: 1e15,
            baseTrackingSupplySpeed: 0,
            baseTrackingBorrowSpeed: 0,
            baseMinForRewards: 1e6,
            baseBorrowMin: 1e6,
            targetReserves: 0,
            assetConfigs: assets
        });

        comet = new CometWithExtendedAssetList(config);
        comet.initializeStorage();   // <- CRITICAL: initializes the indices (otherwise div-by-zero)

        // liquidity in the protocol, so there is something to borrow
        base.allocateTo(address(comet), 5_000_000e6);

        handler = new CometHandler(comet, base, weth);
        targetContract(address(handler));
    }

    /// TRIVIAL step-2 invariant: baseToken is always correct.
    /// The goal is not to catch a bug, but to prove that the invariant machinery works.
    function invariant_sanity_baseTokenConstant() public view {
        assertEq(comet.baseToken(), address(base));
    }

    /// ═══ INV-R1: base accounting consistency ════════════════════════
    /// Σ(principal>0) == totalSupplyBase;  Σ(-principal<0) == totalBorrowBase
    /// We read each actor's REAL principal from Comet and compare it against the totals.
    /// We do not mirror the math — we check the consistency of two places in storage.
    function invariant_R1_basePrincipalMatchesTotals() public view {
        uint256 sumSupply;   // sum of positive principals
        uint256 sumBorrow;   // sum of absolute values of negative principals

        uint256 n = handler.actorsLength();
        for (uint256 i = 0; i < n; i++) {
            address a = handler.actorAt(i);
            // the autogenerated getter of the public userBasic mapping returns a tuple;
            // the first field is the int104 principal
            (int104 principal,,,,) = comet.userBasic(a);
            if (principal > 0) {
                sumSupply += uint256(uint104(principal));
            } else if (principal < 0) {
                sumBorrow += uint256(uint104(-principal));
            }
        }

        CometStorage.TotalsBasic memory totals = CometInterface(address(comet)).totalsBasic();

        // IMPORTANT: in our harness ONLY the actors act (no other user holds a base position),
        // so the sums over actors must exactly equal the global totals.
        assertEq(sumSupply, totals.totalSupplyBase, "R1: supply principal mismatch");
        assertEq(sumBorrow, totals.totalBorrowBase, "R1: borrow principal mismatch");
    }

    /// Shows how many times the fuzzer reached each function (printed at the end).
    function invariant_callSummary() public view {
        console.log("supplyBase calls:   ", handler.callsSupplyBase());
        console.log("withdrawBase calls: ", handler.callsWithdrawBase());
        console.log("supplyColl calls:   ", handler.callsSupplyColl());
    }
}
